### PR TITLE
Fix error when dynamically removing views

### LINKED ISSUE #280: When I used FlexLayout to set constraints for a UITableViewCell, I removed the dataSource of a UITableView and then refreshed the UITableView, which caused a crash. The version of FlexLayout is 2.0.10, and I wonder if this issue is related to YogaKit.
I have obtained the following error log.

terminating due to uncaught exception of type std::logic_error: Cannot set measure function: Nodes with measure functions cannot have children.

### PR DESCRIPTION
**Pull request by heoblitz**
# What is this PR?
Currently, FlexLayout does not guarantee that the UIView hierarchy state matches the Yoga node structure. This is because nodes are only updated during the layout process by following the UIView hierarchy.
When a child UIView is dynamically removed and markDirty() is called, it causes an error and terminates the program because it doesn't align with Yoga's logic.

In React Native's case, views that become leaves are fixed and used consistently, but FlexLayout allows any UIView to become a leaf. Therefore, we add defensive code to prevent logical errors.

# Impact on Existing Users
Without this defensive code, errors were already being triggered by Yoga. In all other cases, the behavior remains identical to the previous version.

close #280

### CODE REVIEW

File: Tests/FlexLayoutTests/FlexLayoutTests.swift [hunk 1]
```diff
@@ -26,5 +26,18 @@ final class FlexLayoutTests: XCTestCase {
...
+        let rootFlexContainer = UIView()
+        rootFlexContainer.flex.addItem(UIView())
+        rootFlexContainer.flex.define { _ in }
+        rootFlexContainer.flex.layout()
+        
+        rootFlexContainer.subviews.forEach { $0.removeFromSuperview() }
+        rootFlexContainer.flex.markDirty()
+        rootFlexContainer.flex.layout()
 
+        XCTAssertTrue(rootFlexContainer.subviews.isEmpty)
```
Comment (heoblitz) [inline Tests/FlexLayoutTests/FlexLayoutTests.swift:41]: Calling markDirty() on rootFlexContainer is unnecessary, but it's an area where users can easily make mistakes.

In the code before this PR, it bypasses the early return condition and causes an error.

File: Sources/YogaKit/YGLayout.mm [hunk 2]
```diff
@@ -227,11 +227,13 @@ - (void)markDirty {
...
   const YGNodeRef node = self.node;
-  if (!YGNodeHasMeasureFunc(node)) {
+  if (!YGNodeHasMeasureFunc(node) && self.numberOfChildren == 0) {
     YGNodeSetMeasureFunc(node, YGMeasureView);
   }
 
-  YGNodeMarkDirty(node);
+  if (YGNodeHasMeasureFunc(node)) {
+    YGNodeMarkDirty(node);
+  }
```
Comment (heoblitz) [inline Sources/YogaKit/YGLayout.mm:236]: I considered modifying the isLeaf logic in YGLayout, but decided not to proceed because there are separate properties being used, making it difficult to guarantee the existing logic.

Therefore, add defensive logic for the assertFatal conditions inside Yoga.

Comment (heoblitz) [reply Sources/YogaKit/YGLayout.mm:236]:
```cpp
void Node::setMeasureFunc(YGMeasureFunc measureFunc) {
  if (measureFunc == nullptr) {
    // TODO: t18095186 Move nodeType to opt-in function and mark appropriate
    // places in Litho
    setNodeType(NodeType::Default);
  } else {
    yoga::assertFatalWithNode(
        this,
        children_.empty(),
        "Cannot set measure function: Nodes with measure functions cannot have "
        "children.");
    // TODO: t18095186 Move nodeType to opt-in function and mark appropriate
    // places in Litho
    setNodeType(NodeType::Text);
  }

  measureFunc_ = measureFunc;
}
```

```cpp
void YGNodeMarkDirty(const YGNodeRef nodeRef) {
  const auto node = resolveRef(nodeRef);

  yoga::assertFatalWithNode(
      node,
      node->hasMeasureFunc(),
      "Only leaf nodes with custom measure functions "
      "should manually mark themselves as dirty");

  node->markDirtyAndPropagate();
}
```

**Review by lucdion — APPROVED** [review]
Thanks 👌
