### PR TITLE
Fix build failure issue on Carthage

### LINKED ISSUE #270: Carthage update Flexlayout as XCFramework fails on Xcode 16.2
Hi, I have recently updated my Xcode to 16.2 and as I have built the Flexlayout on previous version
I got a compiler error.

to solve the problem, I deleted the cache and build files then I tried...

```
 carthage update --platform iOS --use-xcframeworks --no-use-binaries
```

then I get this build error:

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/hwang-in-u/lyrics-app-iOS/Carthage/Checkouts/FlexLayout/FlexLayout.xcworkspace -scheme FlexLayoutInner -configuration Release -derivedDataPath /Users/hwang-in-u/Library/Caches/org.carthage.CarthageKit/DerivedData/16.2_16C5032a/FlexLayout/2.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= SUPPORTS_MACCATALYST=NO CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/87/17d4_w2x2s3536jwhv4g08nh0000gn/T/FlexLayout SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/hwang-in-u/lyrics-app-iOS/Carthage/Checkouts/FlexLayout)

Could I get some help?

### PR DESCRIPTION
**Pull request by heoblitz**
## What is this PR?

Since version 2.1.0, Yoga is managed as a separate dependency, so the project cannot be built on its own. Therefore, it cannot be used with Carthage.

Providing a pre-built static framework or adopting a different structure would require significant changes.
Instead, this PR updates the guide and some settings to maintain the current project structure while enabling Carthage support.

## Test
spm ✅
cocoapods ✅
carthage ✅

[FlexLayoutTest.zip](https://github.com/user-attachments/files/20607329/FlexLayoutTest.zip)

close #270

### CODE REVIEW

File: Podfile [hunk 1]
```diff
@@ -1,5 +1,5 @@
 source 'https://cdn.cocoapods.org/'
-use_frameworks!
+use_frameworks! :linkage => :static
```
Comment (heoblitz) [inline Podfile:2]: Adds configuration to include Yoga inside the xcframework, consistent with the existing wrapping structure.
This change does not affect environments using CocoaPods or Swift Package Manager.

File: Sources/Swift/Public/FlexLayout.h [hunk 2]
```diff
@@ -24,7 +24,7 @@ FOUNDATION_EXPORT double FlexLayoutVersionNumber;
...
 
 // In this header, you should import all the public headers of your framework using
-#import "Yoga.h"
-#import "YGEnums.h"
-#import "YGMacros.h"
-#import "YGValue.h"
+#import <yoga/Yoga.h>
+#import <yoga/YGEnums.h>
+#import <yoga/YGMacros.h>
+#import <yoga/YGValue.h>
```
Comment (heoblitz) [inline Sources/Swift/Public/FlexLayout.h:30]: Updates header import paths to use module paths instead of file paths.

**Comment by heoblitz** [comment]
Hello! @lucdion Would it be possible to invite me to the organization with minimal access?
I'd like to help manage the accumulated issues whenever I have time.
